### ISSUE TITLE
filter error when using python3

### ISSUE THREAD

**Issue by karelv** [pashango2/sphinxcontrib-pandoc-markdown#12]
```
Traceback (most recent call last):
  File "<plugin-path>\remove_caption_filter.py", line 66, in <module>
    toJSONFilter(remove_caption_filter)
  File "<python-path>\lib\site-packages\pandocfilters.py", line 132, in toJSONFilter
    toJSONFilters([action])
  File "<python-path>\lib\site-packages\pandocfilters.py", line 166, in toJSONFilters
    sys.stdout.write(applyJSONFilters(actions, source, format))
  File "<python-path>\lib\site-packages\pandocfilters.py", line 197, in applyJSONFilters
    altered = walk(altered, action, format, meta)
  File "<python-path>\lib\site-packages\pandocfilters.py", line 124, in walk
    x[k] = walk(x[k], action, format, meta)
  File "<python-path>\lib\site-packages\pandocfilters.py", line 113, in walk
    array.append(walk(item, action, format, meta))
  File "<python-path>\lib\site-packages\pandocfilters.py", line 124, in walk
    x[k] = walk(x[k], action, format, meta)
  File "<python-path>\lib\site-packages\pandocfilters.py", line 111, in walk
    item['c'] if 'c' in item else None, format, meta)
  File "<plugin-path>\sphinxcontrib-pandoc-markdown\sphinxcontrib\remove_caption_filter.py", line 54, in remove_caption_filter
    if not bool(urlparse.urlparse(link_path).netloc):
AttributeError: 'function' object has no attribute 'urlparse'
Error running filter <plugin-path>\sphinxcontrib-pandoc-markdown\sphinxcontrib\remove_caption_filter.py:
Filter returned error status 1
```
This is the error I got using python version:
```
$ python -V
Python 3.6.1 :: Anaconda 4.4.0 (64-bit)
```

**Comment by karelv** [comment]
see my pull request: https://github.com/pashango2/sphinxcontrib-pandoc-markdown/pull/13

It solves the issue on my win7 machine.
